// symbols.js — Symbol database only
window.SYMBOLS = (function(){
  var NSE=[
    ['RELIANCE.NS','RELIANCE','Reliance Industries'],
    ['TCS.NS','TCS','Tata Consultancy Services'],
    ['HDFCBANK.NS','HDFCBANK','HDFC Bank'],
    ['INFY.NS','INFY','Infosys'],
    ['ICICIBANK.NS','ICICIBANK','ICICI Bank'],
    ['SBIN.NS','SBIN','State Bank of India'],
    ['KOTAKBANK.NS','KOTAKBANK','Kotak Bank'],
    ['AXISBANK.NS','AXISBANK','Axis Bank'],
    ['BAJFINANCE.NS','BAJFINANCE','Bajaj Finance'],
    ['TATAMOTORS.NS','TATAMOTORS','Tata Motors'],
    ['TATASTEEL.NS','TATASTEEL','Tata Steel'],
    ['WIPRO.NS','WIPRO','Wipro'],
    ['HCLTECH.NS','HCLTECH','HCL Tech'],
    ['SUNPHARMA.NS','SUNPHARMA','Sun Pharma'],
    ['ITC.NS','ITC','ITC Limited'],
    ['MARUTI.NS','MARUTI','Maruti Suzuki'],
    ['LT.NS','LT','Larsen & Toubro'],
    ['BHARTIARTL.NS','BHARTIARTL','Airtel'],
    ['ADANIPORTS.NS','ADANIPORTS','Adani Ports'],
    ['NTPC.NS','NTPC','NTPC'],
    ['POWERGRID.NS','POWERGRID','Power Grid'],
    ['BEL.NS','BEL','Bharat Electronics'],
    ['HAL.NS','HAL','HAL'],
    ['IRCTC.NS','IRCTC','IRCTC'],
    ['RVNL.NS','RVNL','Rail Vikas Nigam'],
    ['ZOMATO.NS','ZOMATO','Zomato'],
    ['HINDUNILVR.NS','HINDUNILVR','HUL'],
    ['NESTLEIND.NS','NESTLEIND','Nestle India'],
    ['TITAN.NS','TITAN','Titan'],
    ['JSWSTEEL.NS','JSWSTEEL','JSW Steel'],
    ['HINDALCO.NS','HINDALCO','Hindalco'],
    ['ONGC.NS','ONGC','ONGC'],
    ['IOC.NS','IOC','Indian Oil'],
    ['COALINDIA.NS','COALINDIA','Coal India'],
    ['IRFC.NS','IRFC','Indian Railway Finance'],
    ['PFC.NS','PFC','Power Finance Corp'],
    ['RECLTD.NS','RECLTD','REC Limited'],
    ['BAJAJFINSV.NS','BAJAJFINSV','Bajaj Finserv'],
    ['HDFCLIFE.NS','HDFCLIFE','HDFC Life'],
    ['SBICARD.NS','SBICARD','SBI Cards'],
    ['DLF.NS','DLF','DLF'],
    ['BANKBARODA.NS','BANKBARODA','Bank of Baroda'],
    ['PNB.NS','PNB','Punjab National Bank'],
    ['INDUSINDBK.NS','INDUSINDBK','IndusInd Bank'],
    ['M&M.NS','M&M','Mahindra & Mahindra'],
    ['EICHERMOT.NS','EICHERMOT','Eicher Motors'],
    ['HEROMOTOCO.NS','HEROMOTOCO','Hero MotoCorp'],
    ['MRF.NS','MRF','MRF'],
    ['PERSISTENT.NS','PERSISTENT','Persistent Systems'],
    ['LTIM.NS','LTIM','LTIMindtree'],
    ['COFORGE.NS','COFORGE','Coforge'],
    ['KPITTECH.NS','KPITTECH','KPIT Technologies'],
    ['DIXON.NS','DIXON','Dixon Technologies'],
    ['GAIL.NS','GAIL','GAIL'],
    ['BPCL.NS','BPCL','BPCL'],
    ['TATAPOWER.NS','TATAPOWER','Tata Power'],
    ['PAYTM.NS','PAYTM','Paytm'],
    ['NYKAA.NS','NYKAA','Nykaa'],
    ['IREDA.NS','IREDA','IREDA'],
    ['LUPIN.NS','LUPIN','Lupin'],
    ['CIPLA.NS','CIPLA','Cipla'],
    ['DRREDDY.NS','DRREDDY',"Dr Reddy"],
    ['DIVISLAB.NS','DIVISLAB',"Divis Lab"],
    ['BIOCON.NS','BIOCON','Biocon'],
    ['ADANIENT.NS','ADANIENT','Adani Enterprises'],
    ['ADANIGREEN.NS','ADANIGREEN','Adani Green'],
    ['ADANIPOWER.NS','ADANIPOWER','Adani Power'],
    ['MUTHOOTFIN.NS','MUTHOOTFIN','Muthoot Finance'],
    ['GODREJPROP.NS','GODREJPROP','Godrej Properties'],
    ['BANDHANBNK.NS','BANDHANBNK','Bandhan Bank'],
    ['FEDERALBNK.NS','FEDERALBNK','Federal Bank'],
    ['IDFCFIRSTB.NS','IDFCFIRSTB','IDFC First Bank'],
    ['RBLBANK.NS','RBLBANK','RBL Bank'],
    ['AUBANK.NS','AUBANK','AU Small Finance'],
    ['ADANIENSOL.NS','ADANIENSOL','Adani Energy Solutions'],
    ['TATACHEM.NS','TATACHEM','Tata Chemicals'],
  ].map(function(a){return{s:a[0],l:a[1],n:a[2],e:'NSE'};});

  var CRYPTO=['BTC','ETH','BNB','XRP','SOL','ADA','DOGE','AVAX','DOT','MATIC',
    'LINK','UNI','ATOM','LTC','BCH','XLM','AAVE','COMP','GRT','NEAR',
    'FTM','ARB','OP','SUI','APT','INJ','PEPE','SHIB','BONK','WIF',
    'ORDI','TIA','WLD','PYTH','THETA','RUNE','ALGO','VET','FIL','TRX',
    'HBAR','SAND','MANA','AXS','CHZ','GALA','FLOKI','MEME',
  ].map(function(b){return{s:b+'USDT',l:b+'USDT',n:b+'/USDT',e:'BINANCE'};});

  var ALL=NSE.concat(CRYPTO);

  return {
    all: function(){return ALL;},
    isIndian: function(s){return s&&(s.indexOf('.NS')>-1||s.indexOf('.BSE')>-1);},
    find: function(s){return ALL.find(function(x){return x.s===s||x.l===s;});},
    search: function(q){
      var Q=q.trim().toUpperCase();
      return Q?ALL.filter(function(x){return x.l.indexOf(Q)>-1||x.n.toUpperCase().indexOf(Q)>-1||x.s.indexOf(Q)>-1;}).slice(0,12):ALL.slice(0,12);
    }
  };
})();
console.log('[SYMBOLS] Loaded:', window.SYMBOLS.all().length);
